[package]
name = "hudhook"
description = "A DirectX 11 render loop hook with memory manipulation API"
homepage = "https://github.com/veeenu/hudhook"
repository = "https://github.com/veeenu/hudhook"
license-file = "LICENSE.md"
version = "0.1.1"
authors = ["Andrea Venuta <venutawebdesign@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "minhook"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
winapi = { version = "0.3.8", features = [ "std", "d3d11", "dxgi", "d3dcompiler", "ntdef", "minwindef", "windef", "psapi", "memoryapi", "synchapi", "winuser", "processthreadsapi" ] }
user32-sys = "0.1"
imgui = "0.4.0"
log = "0.4.8"
simplelog = "0.7.4"
lazy_static = "1.4.0"
itertools = "0.8.1"
log-panics = "2.0.0"

[[example]]
name = "hello_world"
crate-type = ["cdylib"]

[build-dependencies]
cc = "1.0.45"
